#include "AsKeyboard.h"
 
AsString_ref AsKeyboard::KEYNAME_UPARROW(true);
AsString_ref AsKeyboard::KEYNAME_DOWNARROW(true);
AsString_ref AsKeyboard::KEYNAME_LEFTARROW(true);
AsString_ref AsKeyboard::KEYNAME_RIGHTARROW(true);
AsString_ref AsKeyboard::KEYNAME_F1(true);
AsString_ref AsKeyboard::KEYNAME_F2(true);
AsString_ref AsKeyboard::KEYNAME_F3(true);
AsString_ref AsKeyboard::KEYNAME_F4(true);
AsString_ref AsKeyboard::KEYNAME_F5(true);
AsString_ref AsKeyboard::KEYNAME_F6(true);
AsString_ref AsKeyboard::KEYNAME_F7(true);
AsString_ref AsKeyboard::KEYNAME_F8(true);
AsString_ref AsKeyboard::KEYNAME_F9(true);
AsString_ref AsKeyboard::KEYNAME_F10(true);
AsString_ref AsKeyboard::KEYNAME_F11(true);
AsString_ref AsKeyboard::KEYNAME_F12(true);
AsString_ref AsKeyboard::KEYNAME_F13(true);
AsString_ref AsKeyboard::KEYNAME_F14(true);
AsString_ref AsKeyboard::KEYNAME_F15(true);
AsString_ref AsKeyboard::KEYNAME_F16(true);
AsString_ref AsKeyboard::KEYNAME_F17(true);
AsString_ref AsKeyboard::KEYNAME_F18(true);
AsString_ref AsKeyboard::KEYNAME_F19(true);
AsString_ref AsKeyboard::KEYNAME_F20(true);
AsString_ref AsKeyboard::KEYNAME_F21(true);
AsString_ref AsKeyboard::KEYNAME_F22(true);
AsString_ref AsKeyboard::KEYNAME_F23(true);
AsString_ref AsKeyboard::KEYNAME_F24(true);
AsString_ref AsKeyboard::KEYNAME_F25(true);
AsString_ref AsKeyboard::KEYNAME_F26(true);
AsString_ref AsKeyboard::KEYNAME_F27(true);
AsString_ref AsKeyboard::KEYNAME_F28(true);
AsString_ref AsKeyboard::KEYNAME_F29(true);
AsString_ref AsKeyboard::KEYNAME_F30(true);
AsString_ref AsKeyboard::KEYNAME_F31(true);
AsString_ref AsKeyboard::KEYNAME_F32(true);
AsString_ref AsKeyboard::KEYNAME_F33(true);
AsString_ref AsKeyboard::KEYNAME_F34(true);
AsString_ref AsKeyboard::KEYNAME_F35(true);
AsString_ref AsKeyboard::KEYNAME_INSERT(true);
AsString_ref AsKeyboard::KEYNAME_DELETE(true);
AsString_ref AsKeyboard::KEYNAME_HOME(true);
AsString_ref AsKeyboard::KEYNAME_BEGIN(true);
AsString_ref AsKeyboard::KEYNAME_END(true);
AsString_ref AsKeyboard::KEYNAME_PAGEUP(true);
AsString_ref AsKeyboard::KEYNAME_PAGEDOWN(true);
AsString_ref AsKeyboard::KEYNAME_PRINTSCREEN(true);
AsString_ref AsKeyboard::KEYNAME_SCROLLLOCK(true);
AsString_ref AsKeyboard::KEYNAME_PAUSE(true);
AsString_ref AsKeyboard::KEYNAME_SYSREQ(true);
AsString_ref AsKeyboard::KEYNAME_BREAK(true);
AsString_ref AsKeyboard::KEYNAME_RESET(true);
AsString_ref AsKeyboard::KEYNAME_STOP(true);
AsString_ref AsKeyboard::KEYNAME_MENU(true);
AsString_ref AsKeyboard::KEYNAME_USER(true);
AsString_ref AsKeyboard::KEYNAME_SYSTEM(true);
AsString_ref AsKeyboard::KEYNAME_PRINT(true);
AsString_ref AsKeyboard::KEYNAME_CLEARLINE(true);
AsString_ref AsKeyboard::KEYNAME_CLEARDISPLAY(true);
AsString_ref AsKeyboard::KEYNAME_INSERTLINE(true);
AsString_ref AsKeyboard::KEYNAME_DELETELINE(true);
AsString_ref AsKeyboard::KEYNAME_INSERTCHAR(true);
AsString_ref AsKeyboard::KEYNAME_DELETECHAR(true);
AsString_ref AsKeyboard::KEYNAME_PREV(true);
AsString_ref AsKeyboard::KEYNAME_NEXT(true);
AsString_ref AsKeyboard::KEYNAME_SELECT(true);
AsString_ref AsKeyboard::KEYNAME_EXECUTE(true);
AsString_ref AsKeyboard::KEYNAME_UNDO(true);
AsString_ref AsKeyboard::KEYNAME_REDO(true);
AsString_ref AsKeyboard::KEYNAME_FIND(true);
AsString_ref AsKeyboard::KEYNAME_HELP(true);
AsString_ref AsKeyboard::KEYNAME_MODESWITCH(true);
AsString_ref AsKeyboard::STRING_UPARROW(true);
AsString_ref AsKeyboard::STRING_DOWNARROW(true);
AsString_ref AsKeyboard::STRING_LEFTARROW(true);
AsString_ref AsKeyboard::STRING_RIGHTARROW(true);
AsString_ref AsKeyboard::STRING_F1(true);
AsString_ref AsKeyboard::STRING_F2(true);
AsString_ref AsKeyboard::STRING_F3(true);
AsString_ref AsKeyboard::STRING_F4(true);
AsString_ref AsKeyboard::STRING_F5(true);
AsString_ref AsKeyboard::STRING_F6(true);
AsString_ref AsKeyboard::STRING_F7(true);
AsString_ref AsKeyboard::STRING_F8(true);
AsString_ref AsKeyboard::STRING_F9(true);
AsString_ref AsKeyboard::STRING_F10(true);
AsString_ref AsKeyboard::STRING_F11(true);
AsString_ref AsKeyboard::STRING_F12(true);
AsString_ref AsKeyboard::STRING_F13(true);
AsString_ref AsKeyboard::STRING_F14(true);
AsString_ref AsKeyboard::STRING_F15(true);
AsString_ref AsKeyboard::STRING_F16(true);
AsString_ref AsKeyboard::STRING_F17(true);
AsString_ref AsKeyboard::STRING_F18(true);
AsString_ref AsKeyboard::STRING_F19(true);
AsString_ref AsKeyboard::STRING_F20(true);
AsString_ref AsKeyboard::STRING_F21(true);
AsString_ref AsKeyboard::STRING_F22(true);
AsString_ref AsKeyboard::STRING_F23(true);
AsString_ref AsKeyboard::STRING_F24(true);
AsString_ref AsKeyboard::STRING_F25(true);
AsString_ref AsKeyboard::STRING_F26(true);
AsString_ref AsKeyboard::STRING_F27(true);
AsString_ref AsKeyboard::STRING_F28(true);
AsString_ref AsKeyboard::STRING_F29(true);
AsString_ref AsKeyboard::STRING_F30(true);
AsString_ref AsKeyboard::STRING_F31(true);
AsString_ref AsKeyboard::STRING_F32(true);
AsString_ref AsKeyboard::STRING_F33(true);
AsString_ref AsKeyboard::STRING_F34(true);
AsString_ref AsKeyboard::STRING_F35(true);
AsString_ref AsKeyboard::STRING_INSERT(true);
AsString_ref AsKeyboard::STRING_DELETE(true);
AsString_ref AsKeyboard::STRING_HOME(true);
AsString_ref AsKeyboard::STRING_BEGIN(true);
AsString_ref AsKeyboard::STRING_END(true);
AsString_ref AsKeyboard::STRING_PAGEUP(true);
AsString_ref AsKeyboard::STRING_PAGEDOWN(true);
AsString_ref AsKeyboard::STRING_PRINTSCREEN(true);
AsString_ref AsKeyboard::STRING_SCROLLLOCK(true);
AsString_ref AsKeyboard::STRING_PAUSE(true);
AsString_ref AsKeyboard::STRING_SYSREQ(true);
AsString_ref AsKeyboard::STRING_BREAK(true);
AsString_ref AsKeyboard::STRING_RESET(true);
AsString_ref AsKeyboard::STRING_STOP(true);
AsString_ref AsKeyboard::STRING_MENU(true);
AsString_ref AsKeyboard::STRING_USER(true);
AsString_ref AsKeyboard::STRING_SYSTEM(true);
AsString_ref AsKeyboard::STRING_PRINT(true);
AsString_ref AsKeyboard::STRING_CLEARLINE(true);
AsString_ref AsKeyboard::STRING_CLEARDISPLAY(true);
AsString_ref AsKeyboard::STRING_INSERTLINE(true);
AsString_ref AsKeyboard::STRING_DELETELINE(true);
AsString_ref AsKeyboard::STRING_INSERTCHAR(true);
AsString_ref AsKeyboard::STRING_DELETECHAR(true);
AsString_ref AsKeyboard::STRING_PREV(true);
AsString_ref AsKeyboard::STRING_NEXT(true);
AsString_ref AsKeyboard::STRING_SELECT(true);
AsString_ref AsKeyboard::STRING_EXECUTE(true);
AsString_ref AsKeyboard::STRING_UNDO(true);
AsString_ref AsKeyboard::STRING_REDO(true);
AsString_ref AsKeyboard::STRING_FIND(true);
AsString_ref AsKeyboard::STRING_HELP(true);
AsString_ref AsKeyboard::STRING_MODESWITCH(true);
 
bool AsKeyboard::_as_static_initialized_AsKeyboard = false;
AsStaticRefInitializer AsKeyboard::_as_static_initializer_AsKeyboard(_as_static_init_AsKeyboard);
void AsKeyboard::_as_static_init_AsKeyboard()
{
	if (!_as_static_initialized_AsKeyboard)
	{
		_as_static_initialized_AsKeyboard = true;
		
		KEYNAME_UPARROW = ASL("Up");
		KEYNAME_DOWNARROW = ASL("Down");
		KEYNAME_LEFTARROW = ASL("Left");
		KEYNAME_RIGHTARROW = ASL("Right");
		KEYNAME_F1 = ASL("F1");
		KEYNAME_F2 = ASL("F2");
		KEYNAME_F3 = ASL("F3");
		KEYNAME_F4 = ASL("F4");
		KEYNAME_F5 = ASL("F5");
		KEYNAME_F6 = ASL("F6");
		KEYNAME_F7 = ASL("F7");
		KEYNAME_F8 = ASL("F8");
		KEYNAME_F9 = ASL("F9");
		KEYNAME_F10 = ASL("F10");
		KEYNAME_F11 = ASL("F11");
		KEYNAME_F12 = ASL("F12");
		KEYNAME_F13 = ASL("F13");
		KEYNAME_F14 = ASL("F14");
		KEYNAME_F15 = ASL("F15");
		KEYNAME_F16 = ASL("F16");
		KEYNAME_F17 = ASL("F17");
		KEYNAME_F18 = ASL("F18");
		KEYNAME_F19 = ASL("F19");
		KEYNAME_F20 = ASL("F20");
		KEYNAME_F21 = ASL("F21");
		KEYNAME_F22 = ASL("F22");
		KEYNAME_F23 = ASL("F23");
		KEYNAME_F24 = ASL("F24");
		KEYNAME_F25 = ASL("F25");
		KEYNAME_F26 = ASL("F26");
		KEYNAME_F27 = ASL("F27");
		KEYNAME_F28 = ASL("F28");
		KEYNAME_F29 = ASL("F29");
		KEYNAME_F30 = ASL("F30");
		KEYNAME_F31 = ASL("F31");
		KEYNAME_F32 = ASL("F32");
		KEYNAME_F33 = ASL("F33");
		KEYNAME_F34 = ASL("F34");
		KEYNAME_F35 = ASL("F35");
		KEYNAME_INSERT = ASL("Insert");
		KEYNAME_DELETE = ASL("Delete");
		KEYNAME_HOME = ASL("Home");
		KEYNAME_BEGIN = ASL("Begin");
		KEYNAME_END = ASL("End");
		KEYNAME_PAGEUP = ASL("PgUp");
		KEYNAME_PAGEDOWN = ASL("PgDn");
		KEYNAME_PRINTSCREEN = ASL("PrntScrn");
		KEYNAME_SCROLLLOCK = ASL("ScrlLck");
		KEYNAME_PAUSE = ASL("Pause");
		KEYNAME_SYSREQ = ASL("SysReq");
		KEYNAME_BREAK = ASL("Break");
		KEYNAME_RESET = ASL("Reset");
		KEYNAME_STOP = ASL("Stop");
		KEYNAME_MENU = ASL("Menu");
		KEYNAME_USER = ASL("User");
		KEYNAME_SYSTEM = ASL("Sys");
		KEYNAME_PRINT = ASL("Print");
		KEYNAME_CLEARLINE = ASL("ClrLn");
		KEYNAME_CLEARDISPLAY = ASL("ClrDsp");
		KEYNAME_INSERTLINE = ASL("InsLn");
		KEYNAME_DELETELINE = ASL("DelLn");
		KEYNAME_INSERTCHAR = ASL("InsChr");
		KEYNAME_DELETECHAR = ASL("DelChr");
		KEYNAME_PREV = ASL("Prev");
		KEYNAME_NEXT = ASL("Next");
		KEYNAME_SELECT = ASL("Select");
		KEYNAME_EXECUTE = ASL("Exec");
		KEYNAME_UNDO = ASL("Undo");
		KEYNAME_REDO = ASL("Redo");
		KEYNAME_FIND = ASL("Find");
		KEYNAME_HELP = ASL("Help");
		KEYNAME_MODESWITCH = ASL("ModeSw");
		STRING_UPARROW = ASL("");
		STRING_DOWNARROW = ASL("");
		STRING_LEFTARROW = ASL("");
		STRING_RIGHTARROW = ASL("");
		STRING_F1 = ASL("");
		STRING_F2 = ASL("");
		STRING_F3 = ASL("");
		STRING_F4 = ASL("");
		STRING_F5 = ASL("");
		STRING_F6 = ASL("");
		STRING_F7 = ASL("");
		STRING_F8 = ASL("");
		STRING_F9 = ASL("");
		STRING_F10 = ASL("");
		STRING_F11 = ASL("");
		STRING_F12 = ASL("");
		STRING_F13 = ASL("");
		STRING_F14 = ASL("");
		STRING_F15 = ASL("");
		STRING_F16 = ASL("");
		STRING_F17 = ASL("");
		STRING_F18 = ASL("");
		STRING_F19 = ASL("");
		STRING_F20 = ASL("");
		STRING_F21 = ASL("");
		STRING_F22 = ASL("");
		STRING_F23 = ASL("");
		STRING_F24 = ASL("");
		STRING_F25 = ASL("");
		STRING_F26 = ASL("");
		STRING_F27 = ASL("");
		STRING_F28 = ASL("");
		STRING_F29 = ASL("");
		STRING_F30 = ASL("");
		STRING_F31 = ASL("");
		STRING_F32 = ASL("");
		STRING_F33 = ASL("");
		STRING_F34 = ASL("");
		STRING_F35 = ASL("");
		STRING_INSERT = ASL("");
		STRING_DELETE = ASL("");
		STRING_HOME = ASL("");
		STRING_BEGIN = ASL("");
		STRING_END = ASL("");
		STRING_PAGEUP = ASL("");
		STRING_PAGEDOWN = ASL("");
		STRING_PRINTSCREEN = ASL("");
		STRING_SCROLLLOCK = ASL("");
		STRING_PAUSE = ASL("");
		STRING_SYSREQ = ASL("");
		STRING_BREAK = ASL("");
		STRING_RESET = ASL("");
		STRING_STOP = ASL("");
		STRING_MENU = ASL("");
		STRING_USER = ASL("");
		STRING_SYSTEM = ASL("");
		STRING_PRINT = ASL("");
		STRING_CLEARLINE = ASL("");
		STRING_CLEARDISPLAY = ASL("");
		STRING_INSERTLINE = ASL("");
		STRING_DELETELINE = ASL("");
		STRING_INSERTCHAR = ASL("");
		STRING_DELETECHAR = ASL("");
		STRING_PREV = ASL("");
		STRING_NEXT = ASL("");
		STRING_SELECT = ASL("");
		STRING_EXECUTE = ASL("");
		STRING_UNDO = ASL("");
		STRING_REDO = ASL("");
		STRING_FIND = ASL("");
		STRING_HELP = ASL("");
		STRING_MODESWITCH = ASL("");
	}
}
