#ifndef AsKeyboard_h__
#define AsKeyboard_h__
 
#include "AsBc.h"
 
#include "AsObject.h"
 
#include "AsString.h"
 
 
AS_CLASS(AsKeyboard);
 
class AsKeyboard : public AsObject
{
public:
	AS_OBJ(AsKeyboard, AsObject);
	
public:
	static AsString_ref KEYNAME_UPARROW;
	static AsString_ref KEYNAME_DOWNARROW;
	static AsString_ref KEYNAME_LEFTARROW;
	static AsString_ref KEYNAME_RIGHTARROW;
	static AsString_ref KEYNAME_F1;
	static AsString_ref KEYNAME_F2;
	static AsString_ref KEYNAME_F3;
	static AsString_ref KEYNAME_F4;
	static AsString_ref KEYNAME_F5;
	static AsString_ref KEYNAME_F6;
	static AsString_ref KEYNAME_F7;
	static AsString_ref KEYNAME_F8;
	static AsString_ref KEYNAME_F9;
	static AsString_ref KEYNAME_F10;
	static AsString_ref KEYNAME_F11;
	static AsString_ref KEYNAME_F12;
	static AsString_ref KEYNAME_F13;
	static AsString_ref KEYNAME_F14;
	static AsString_ref KEYNAME_F15;
	static AsString_ref KEYNAME_F16;
	static AsString_ref KEYNAME_F17;
	static AsString_ref KEYNAME_F18;
	static AsString_ref KEYNAME_F19;
	static AsString_ref KEYNAME_F20;
	static AsString_ref KEYNAME_F21;
	static AsString_ref KEYNAME_F22;
	static AsString_ref KEYNAME_F23;
	static AsString_ref KEYNAME_F24;
	static AsString_ref KEYNAME_F25;
	static AsString_ref KEYNAME_F26;
	static AsString_ref KEYNAME_F27;
	static AsString_ref KEYNAME_F28;
	static AsString_ref KEYNAME_F29;
	static AsString_ref KEYNAME_F30;
	static AsString_ref KEYNAME_F31;
	static AsString_ref KEYNAME_F32;
	static AsString_ref KEYNAME_F33;
	static AsString_ref KEYNAME_F34;
	static AsString_ref KEYNAME_F35;
	static AsString_ref KEYNAME_INSERT;
	static AsString_ref KEYNAME_DELETE;
	static AsString_ref KEYNAME_HOME;
	static AsString_ref KEYNAME_BEGIN;
	static AsString_ref KEYNAME_END;
	static AsString_ref KEYNAME_PAGEUP;
	static AsString_ref KEYNAME_PAGEDOWN;
	static AsString_ref KEYNAME_PRINTSCREEN;
	static AsString_ref KEYNAME_SCROLLLOCK;
	static AsString_ref KEYNAME_PAUSE;
	static AsString_ref KEYNAME_SYSREQ;
	static AsString_ref KEYNAME_BREAK;
	static AsString_ref KEYNAME_RESET;
	static AsString_ref KEYNAME_STOP;
	static AsString_ref KEYNAME_MENU;
	static AsString_ref KEYNAME_USER;
	static AsString_ref KEYNAME_SYSTEM;
	static AsString_ref KEYNAME_PRINT;
	static AsString_ref KEYNAME_CLEARLINE;
	static AsString_ref KEYNAME_CLEARDISPLAY;
	static AsString_ref KEYNAME_INSERTLINE;
	static AsString_ref KEYNAME_DELETELINE;
	static AsString_ref KEYNAME_INSERTCHAR;
	static AsString_ref KEYNAME_DELETECHAR;
	static AsString_ref KEYNAME_PREV;
	static AsString_ref KEYNAME_NEXT;
	static AsString_ref KEYNAME_SELECT;
	static AsString_ref KEYNAME_EXECUTE;
	static AsString_ref KEYNAME_UNDO;
	static AsString_ref KEYNAME_REDO;
	static AsString_ref KEYNAME_FIND;
	static AsString_ref KEYNAME_HELP;
	static AsString_ref KEYNAME_MODESWITCH;
	static AsString_ref STRING_UPARROW;
	static AsString_ref STRING_DOWNARROW;
	static AsString_ref STRING_LEFTARROW;
	static AsString_ref STRING_RIGHTARROW;
	static AsString_ref STRING_F1;
	static AsString_ref STRING_F2;
	static AsString_ref STRING_F3;
	static AsString_ref STRING_F4;
	static AsString_ref STRING_F5;
	static AsString_ref STRING_F6;
	static AsString_ref STRING_F7;
	static AsString_ref STRING_F8;
	static AsString_ref STRING_F9;
	static AsString_ref STRING_F10;
	static AsString_ref STRING_F11;
	static AsString_ref STRING_F12;
	static AsString_ref STRING_F13;
	static AsString_ref STRING_F14;
	static AsString_ref STRING_F15;
	static AsString_ref STRING_F16;
	static AsString_ref STRING_F17;
	static AsString_ref STRING_F18;
	static AsString_ref STRING_F19;
	static AsString_ref STRING_F20;
	static AsString_ref STRING_F21;
	static AsString_ref STRING_F22;
	static AsString_ref STRING_F23;
	static AsString_ref STRING_F24;
	static AsString_ref STRING_F25;
	static AsString_ref STRING_F26;
	static AsString_ref STRING_F27;
	static AsString_ref STRING_F28;
	static AsString_ref STRING_F29;
	static AsString_ref STRING_F30;
	static AsString_ref STRING_F31;
	static AsString_ref STRING_F32;
	static AsString_ref STRING_F33;
	static AsString_ref STRING_F34;
	static AsString_ref STRING_F35;
	static AsString_ref STRING_INSERT;
	static AsString_ref STRING_DELETE;
	static AsString_ref STRING_HOME;
	static AsString_ref STRING_BEGIN;
	static AsString_ref STRING_END;
	static AsString_ref STRING_PAGEUP;
	static AsString_ref STRING_PAGEDOWN;
	static AsString_ref STRING_PRINTSCREEN;
	static AsString_ref STRING_SCROLLLOCK;
	static AsString_ref STRING_PAUSE;
	static AsString_ref STRING_SYSREQ;
	static AsString_ref STRING_BREAK;
	static AsString_ref STRING_RESET;
	static AsString_ref STRING_STOP;
	static AsString_ref STRING_MENU;
	static AsString_ref STRING_USER;
	static AsString_ref STRING_SYSTEM;
	static AsString_ref STRING_PRINT;
	static AsString_ref STRING_CLEARLINE;
	static AsString_ref STRING_CLEARDISPLAY;
	static AsString_ref STRING_INSERTLINE;
	static AsString_ref STRING_DELETELINE;
	static AsString_ref STRING_INSERTCHAR;
	static AsString_ref STRING_DELETECHAR;
	static AsString_ref STRING_PREV;
	static AsString_ref STRING_NEXT;
	static AsString_ref STRING_SELECT;
	static AsString_ref STRING_EXECUTE;
	static AsString_ref STRING_UNDO;
	static AsString_ref STRING_REDO;
	static AsString_ref STRING_FIND;
	static AsString_ref STRING_HELP;
	static AsString_ref STRING_MODESWITCH;
	static const uint NUMBER_0 = 48;
	static const uint NUMBER_1 = 49;
	static const uint NUMBER_2 = 50;
	static const uint NUMBER_3 = 51;
	static const uint NUMBER_4 = 52;
	static const uint NUMBER_5 = 53;
	static const uint NUMBER_6 = 54;
	static const uint NUMBER_7 = 55;
	static const uint NUMBER_8 = 56;
	static const uint NUMBER_9 = 57;
	static const uint A = 65;
	static const uint B = 66;
	static const uint C = 67;
	static const uint D = 68;
	static const uint E = 69;
	static const uint F = 70;
	static const uint G = 71;
	static const uint H = 72;
	static const uint I = 73;
	static const uint J = 74;
	static const uint K = 75;
	static const uint L = 76;
	static const uint M = 77;
	static const uint N = 78;
	static const uint O = 79;
	static const uint P = 80;
	static const uint Q = 81;
	static const uint R = 82;
	static const uint S = 83;
	static const uint T = 84;
	static const uint U = 85;
	static const uint V = 86;
	static const uint W = 87;
	static const uint X = 88;
	static const uint Y = 89;
	static const uint Z = 90;
	static const uint SEMICOLON = 186;
	static const uint EQUAL = 187;
	static const uint COMMA = 188;
	static const uint MINUS = 189;
	static const uint PERIOD = 190;
	static const uint SLASH = 191;
	static const uint BACKQUOTE = 192;
	static const uint LEFTBRACKET = 219;
	static const uint BACKSLASH = 220;
	static const uint RIGHTBRACKET = 221;
	static const uint QUOTE = 222;
	static const uint ALTERNATE = 18;
	static const uint BACKSPACE = 8;
	static const uint CAPS_LOCK = 20;
	static const uint COMMAND = 15;
	static const uint CONTROL = 17;
	static const uint DELETE = 46;
	static const uint DOWN = 40;
	static const uint END = 35;
	static const uint ENTER = 13;
	static const uint ESCAPE = 27;
	static const uint F1 = 112;
	static const uint F2 = 113;
	static const uint F3 = 114;
	static const uint F4 = 115;
	static const uint F5 = 116;
	static const uint F6 = 117;
	static const uint F7 = 118;
	static const uint F8 = 119;
	static const uint F9 = 120;
	static const uint F10 = 121;
	static const uint F11 = 122;
	static const uint F12 = 123;
	static const uint F13 = 124;
	static const uint F14 = 125;
	static const uint F15 = 126;
	static const uint HOME = 36;
	static const uint INSERT = 45;
	static const uint LEFT = 37;
	static const uint NUMPAD = 21;
	static const uint NUMPAD_0 = 96;
	static const uint NUMPAD_1 = 97;
	static const uint NUMPAD_2 = 98;
	static const uint NUMPAD_3 = 99;
	static const uint NUMPAD_4 = 100;
	static const uint NUMPAD_5 = 101;
	static const uint NUMPAD_6 = 102;
	static const uint NUMPAD_7 = 103;
	static const uint NUMPAD_8 = 104;
	static const uint NUMPAD_9 = 105;
	static const uint NUMPAD_ADD = 107;
	static const uint NUMPAD_DECIMAL = 110;
	static const uint NUMPAD_DIVIDE = 111;
	static const uint NUMPAD_ENTER = 108;
	static const uint NUMPAD_MULTIPLY = 106;
	static const uint NUMPAD_SUBTRACT = 109;
	static const uint PAGE_DOWN = 34;
	static const uint PAGE_UP = 33;
	static const uint RIGHT = 39;
	static const uint SHIFT = 16;
	static const uint SPACE = 32;
	static const uint TAB = 9;
	static const uint UP = 38;
	static const uint RED = 16777216;
	static const uint GREEN = 16777217;
	static const uint YELLOW = 16777218;
	static const uint BLUE = 16777219;
	static const uint CHANNEL_UP = 16777220;
	static const uint CHANNEL_DOWN = 16777221;
	static const uint RECORD = 16777222;
	static const uint PLAY = 16777223;
	static const uint PAUSE = 16777224;
	static const uint STOP = 16777225;
	static const uint FAST_FORWARD = 16777226;
	static const uint REWIND = 16777227;
	static const uint SKIP_FORWARD = 16777228;
	static const uint SKIP_BACKWARD = 16777229;
	static const uint NEXT = 16777230;
	static const uint PREVIOUS = 16777231;
	static const uint LIVE = 16777232;
	static const uint LAST = 16777233;
	static const uint MENU = 16777234;
	static const uint INFO = 16777235;
	static const uint GUIDE = 16777236;
	static const uint EXIT = 16777237;
	static const uint BACK = 16777238;
	static const uint AUDIO = 16777239;
	static const uint SUBTITLE = 16777240;
	static const uint DVR = 16777241;
	static const uint VOD = 16777242;
	static const uint INPUT = 16777243;
	static const uint SETUP = 16777244;
	static const uint HELP = 16777245;
	static const uint MASTER_SHELL = 16777246;
	static const uint SEARCH = 16777247;
	
	static void _as_static_init_AsKeyboard();
	
private:
	static bool _as_static_initialized_AsKeyboard;
	static AsStaticRefInitializer _as_static_initializer_AsKeyboard;
};
 
#endif // AsKeyboard_h__
